# Generated by Django 2.2.16 on 2022-10-07 00:00

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221006_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digitsand @/./+/-/_ only.', max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='username'),
        ),
    ]
