# Generated by Django 2.2.16 on 2022-10-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_genretitle'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genretitle',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='genre_title'),
        ),
    ]
