# Generated by Django 2.2.16 on 2022-10-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221006_1051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genretitle',
            name='genre_title',
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.Title'),
        ),
    ]
